export const GET_PARKING_PENDING = "GET_PARKING_PENDING";
export const GET_PARKING_SUCCESS = "GET_PARKING_SUCCESS";
export const GET_PARKING_FAIL = "GET_PARKING_FAIL";

export const SET_PARKING_OPTIONS = "SET_PARKING_OPTIONS";